### ISSUE TITLE
Upgrading dependency from 2.0.0-2 to 2.0.0-3 causes class not found exception

### ISSUE THREAD

**Issue by pellcorp** [nqzero/kilim#6]
I am currently working through migrating our application from an internally compiled version of kilim (based on https://github.com/kilim/kilim/tree/asm5-jdk8) to the org.db4j kilim version deployed to maven central.

We have some test cases that fail when we upgrade from 2.0.0-2 to 2.0.0-3.  With the following exception:

java.lang.NoClassDefFoundError: kilim/S_O4
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

I will spend some time narrowing down exactly which particular code causes this failure but I thought I would raise this issue now and see if you knew off hand why it might be occurring to save me some time.

**Comment by pellcorp** [comment]
I should add that I had started with 2.0.0-15 with the same issue, I narrowed it down to something that has changed between 2.0.0-2 and 2.0.0-3 and above.

**Comment by nqzero** [comment]
2.0.0-2 to 2.0.0-3 isn't a huge change, but it merges the runtime weaver and ahead-of-time weaver into a single weaver based primarily on the runtime weaver. are you able to share your test ? or are you weaving using the plugin or the runtime weaver ? i believe that i did see similar issues at some point but don't remember the cause or how i resolved them

**Comment by nqzero** [comment]
S_04 is a class that kilim generates when it detects that it is needed (it represents the state pushed on to the stack). so the cause could be either that it's incorrectly deciding not to generate it during weaving (but it's needed at runtime) or incorrectly deciding that it's needed at runtime

what build procedure are you using for kilim ? are your tests run as part of the kilim build or are they external ?

the build is a hybrid as mentioned in the readme. maven is used to download dependencies and maven can perform the build. but under maven, the kilim tests don't run - you need to use ant for that

are you interested in sharing your modifications ? it's possible that i'd be willing to integrate them into the core package. if they're bug fixes for the rtweaver, it's possible that they've already been fixed

**Comment by pellcorp** [comment]
I have no modifications to contribute at this point, we were looking to swap in your kilim distribution to replace our locally compiled version of the original java 8 work done by @sriram-srinivasan, no local changes were made to this branch, we just compiled and produced an internal maven jar file.

I don't believe I can provide the failing test case in its current form as its too dependent on the rest of our code base which is proprietary.

I am currently doing some bisecting to determine exactly which commit causes our tests to break, I will then be in a better position to determine exactly what is going wrong.

We do code generation.   We take a DSL describing a set of nodes and produce an equivalent set of kilim actors which are then pre-weaved.

 I have one particular set of tests that are currently breaking with 2.0.0-3, but not all of my tests are breaking.  

So it will take me some time to determine exactly what feature of kilim I am using that is at issue.

**Comment by pellcorp** [comment]
I have narrowed down the problematic commit to:

commit 407e52b7ae1e77aa0c98730a8d28a41b13b2e68e (HEAD)
Author: lytles@takashi <srl.source@nqzero.com>
Date:   Sat Oct 22 13:21:40 2016 -0400

issues.49 - restore local vars: assume try block defs can be skipped once a var is born in liveness calc

**Comment by nqzero** [comment]
ClassWeaver.createStateClass creates the class bytecode at the same time the name is generated and then the bytecode gets written out by Weaver. i don't see major changes in this area in that range of commits, so i'm guessing the issue is either a stale file or a classpath

one change in that range of commits is the weaver now uses timestamps, so it could be a stale class file (use -f to force weaving even if up to date or make sure you have a clean build each time). liveness analysis has improved, so it's possible that that StateClass is no longer needed. are the other kilim/S_ class files being generated ?

how are you weaving, eg command line, ant task, my maven plugin, the older maven plugin ?

**Comment by pellcorp** [comment]
We are doing weaving in a rather unique way.  We do code generation at runtime in memory and then compile in memory using the javax.tools.JavaCompiler, and then we weave these files in memory too using a custom classloader as well.

But this process works for a lot of other generated code, so I am guessing something in the commit I identified affects a very specific use case in our code generation.

I am planning to see if I can isolate a test case without IP issues that reproduces the problem, but thats going to take me a day or two I suspect.

**Comment by nqzero** [comment]
the liveness calculation is going to affect which state class is generated, but the weaving is a separate pass and the generation and consumption of the state class happen at the same point, so i'm struggling to think how the liveness could lead to the exception that you're seeing

a test case would be great - sriram and i have talked about how hard it is to generate tests (your DSL approach has me thinking we may want to head that direction for some sort of fuzzing). that said, i hate to cost you a day or 2 of working on it

does the exception happen during the weaving or the running of the generated code ? could you run under a debugger and set a breakpoint in createStateClass ?

is your custom classloader definitive or does it delegate to a parent ? eg, look at kilim.WeavingClassLoader. after weaving, do you write the classes out to files ?

this is the end of my day (USTZ) so those questions are somewhat rhetorical

**Comment by pellcorp** [comment]
The exception happens when running the code.  Just constructing the actor in the junit setup method causes it I don't even get to execute the actor logic

**Comment by pellcorp** [comment]
ok, it has to be something specific to how we are using kilim, I swapped in your maven plugin to my test case and it stopped failing.

So at this point I think the problem has to be on our side.  Time to start digging.

**Comment by pellcorp** [comment]
ok, so this was not a bug in kilim, but in the way we were using kilim.  Problem was in older versions the S_ classes were in the kilim.jar file, wereas in the org.db4j.kilim releases they are generated at weaving time as required.  We were not including these into the class path in our maven plugin.

I apologise for this really stupid bug report!

**Comment by nqzero** [comment]
i should have thought of that (or expressed my "staleness" theory better). the bundling hasn't changed - kilim still bundles the S_ classes that it uses and S_O3 is bundled but S_O4 isn't. but the improved liveness calculation in 2.0.0-3 meant that the state classes your code required changed. in some corner cases involving loops and try/catch blocks, kilim 1.0 used to drop state and give incorrect results. so the good news is that you could have gotten incorrect results with 1.0 and 2.0 should be giving you the correct results (in theory this could cause you trouble in some downstream processing, so buyer beware)

not stupid at all - at worst, it's good to get some insight into how kilim is being used
